spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/travel?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&allowPublicKeyRetrieval=true
    username: root
    password: root

  flyway:
    enabled: true
    repair: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true

  openfire:
    host: localhost
    port: 5222
    domain: localhost
    security-mode: disabled
    admin:
      username: admin
      password: admin